django_project/core/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from django.views.i18n import javascript_catalog
from realtime.admin import realtime_admin_site


js_info_dict = {
    'packages': ('realtime',),
}

urlpatterns = patterns(
    '',

    url(r'^admin/', include(admin.site.urls)),

    # uncomment to enable defaut Django auth
    # url(r'^accounts/login/$', 'django.contrib.auth.views.login'),

    # include application urls
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'', include('frontend.urls', namespace='front_end')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^mce_filebrowser/', include('mce_filebrowser.urls')),
    url(r'^user-map/', include('user_map.urls', namespace='user_map')),
    url(r'^jsi18n/$', javascript_catalog, js_info_dict),
    url(r'^realtime/', include('realtime.urls', namespace='realtime')),
    url(r'^realtime/api-auth/', include(
        'rest_framework.urls', namespace='rest_framework')),
    # alias for auth in realtime
    url(r'^realtime/api/v1/auth/', include(
        'rest_framework.urls', namespace='rest_framework')),
    url(r'^realtime/admin/', include(realtime_admin_site.urls)),

    # url pattern for realtime reports
    url(r'', include('realtime.report_urls', namespace='realtime_report')),

    # url pattern for realtime flatpages
    # not appending slash because flatpages url starts with one
    url(r'^realtime/pages', include('django.contrib.flatpages.urls')),
)

# expose static files and uploded media if DEBUG is active
if settings.DEBUG:
    urlpatterns += patterns(
        '',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {
                'document_root': settings.MEDIA_ROOT,
                'show_indexes': True
            }),
        url(r'', include('django.contrib.staticfiles.urls'))
    )
else:
    # for production mode
    # Although it will also be served by nginx
    # Useful for testing production environment in local configuration
    urlpatterns += patterns(
        '',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {
                'document_root': settings.MEDIA_ROOT,
                'show_indexes': False
            }),
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
            {
                'document_root': settings.STATIC_ROOT,
                'show_indexes': False
            }),
    )

django_project/user_map/urls.py
# coding=utf-8
"""URI Routing configuration for this apps."""
from django.conf.urls import patterns, url

urlpatterns = patterns(
    '',
    url(r'^$', 'user_map.views.index', name='index'),
    url(r'^users.json', 'user_map.views.get_users', name='get_users'),

    url(r'^register$', 'user_map.views.register', name='register'),
    url(r'^account-confirmation/(?P<uid>[0-9A-Za-z_\-]+)/(?P<key>.+)/$',
        'user_map.views.confirm_registration',
        name='confirm_registration'),

    url(r'^login$', 'user_map.views.login', name='login'),
    url(r'^logout$', 'user_map.views.logout', name='logout'),
    url(r'^update-profile$', 'user_map.views.update_user', name='update_user'),
    url(r'^delete-user$', 'user_map.views.delete_user', name='delete_user'),

    url(r'^password-reset/$', 'user_map.views.password_reset',
        name='password_reset'),
    url(r'^password-reset/done/$', 'user_map.views.password_reset_done',
        name='password_reset_done'),
    url(r'^password-reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
        'user_map.views.password_reset_confirm',
        name='password_reset_confirm'),
    url(r'^password-reset/complete/$',
        'user_map.views.password_reset_complete',
        name='password_reset_complete'),

    url(r'^download$', 'user_map.views.download', name='download'),
)

django_project/user_map/models/inasafe_role.py
# coding=utf-8
"""Model class for InaSAFE Role"""
from django.contrib.gis.db import models


class InasafeRole(models.Model):
    """InaSAFE Role for users e.g. InaSAFE developer, trainer, user."""
    class Meta:
        """Meta class."""
        app_label = 'user_map'

    name = models.CharField(
        help_text='How would you define your InaSAFE Role in this project?',
        max_length=100,
        null=False,
        blank=False)
    badge = models.CharField(
        help_text='The path to the badge',
        max_length=200,
        null=False,
        blank=False)
    sort_number = models.IntegerField(
        help_text='Sorting order for role in role list.',
        null=True,
        blank=True)

    def __unicode__(self):
        return self.name

django_project/user_map/models/osm_role.py
# coding=utf-8
"""Model class for OSM Role"""
from django.contrib.gis.db import models


class OsmRole(models.Model):
    """OSM Role for users e.g. OSM Mapper, Trainer."""
    class Meta:
        """Meta class."""
        app_label = 'user_map'

    name = models.CharField(
        help_text='How would you define your OSM Role in this project?',
        max_length=100,
        null=False,
        blank=False)
    badge = models.CharField(
        help_text='The path to the badge',
        max_length=100,
        null=False,
        blank=False)
    sort_number = models.IntegerField(
        help_text='Sorting order for role in role list.',
        null=True,
        blank=True)

    def __unicode__(self):
        return self.name

django_project/user_map/forms/custom_widget.py
from django.utils.safestring import mark_safe
from django.utils.html import escape, conditional_escape
from django.utils.encoding import force_unicode
from django.forms.widgets import ClearableFileInput, Input, CheckboxInput


class CustomClearableFileInput(ClearableFileInput):
    """A custom ClearableFileInput widget.

    ..note:: Adapted from django.forms.widgets.ClearableFileInput and also
        utilising img-responsive bootstrap class.
    """
    def render(self, name, value, attrs=None):
        """Render the custom widget."""
        substitutions = {
            'input_text': self.input_text,
            'clear_template': '',
            'clear_checkbox_label': self.clear_checkbox_label,
        }
        template = '%(input)s'
        substitutions['input'] = Input.render(self, name, value, attrs)

        if value and hasattr(value, "url"):
            template = ('%(initial)s %(clear_template)s<br />%(input_text)s: '
                        '%(input)s')
            substitutions['initial'] = (
                '<img class="img-responsive" src="%s" alt="%s"/>' % (
                    escape(value.url), escape(force_unicode(value))))
            if not self.is_required:
                checkbox_name = self.clear_checkbox_name(name)
                checkbox_id = self.clear_checkbox_id(checkbox_name)
                substitutions['clear_checkbox_name'] = conditional_escape(
                    checkbox_name)
                substitutions['clear_checkbox_id'] = conditional_escape(
                    checkbox_id)
                substitutions['clear'] = CheckboxInput().render(
                    checkbox_name, False, attrs={'id': checkbox_id})
                substitutions['clear_template'] = \
                    self.template_with_clear % substitutions
        return mark_safe(template % substitutions)

django_project/user_map/views.py
# coding=utf-8
"""Views of the apps."""
import unicodecsv as csv

from django.shortcuts import render, render_to_response
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.template import RequestContext, loader
from django.forms.util import ErrorList
from django.forms.forms import NON_FIELD_ERRORS
from django.core.urlresolvers import reverse
from django.core.mail import send_mail
from django.contrib import messages
from django.contrib.auth import (
    login as django_login,
    authenticate,
    logout as django_logout)
from django.contrib.auth.views import (
    password_reset as django_password_reset,
    password_reset_done as django_password_reset_done,
    password_reset_confirm as django_password_reset_confirm,
    password_reset_complete as django_password_reset_complete)
from django.contrib.auth.forms import PasswordChangeForm, SetPasswordForm
from django.contrib.auth.decorators import login_required
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.sites.models import get_current_site
from realtime.app_settings import REST_GROUP

from user_map.forms.user import (
    RegistrationForm,
    LoginForm,
    BasicInformationForm,
    CustomPasswordResetForm)
from user_map.models.user import User
from user_map.app_settings import (
    PROJECT_NAME,
    PROJECTS,
    INASAFE_CERTIFIED_TRAINER_BADGE,
    OSM_CERTIFIED_TRAINER_BADGE,
    DEFAULT_FROM_MAIL,
    LEAFLET_TILES, MAPQUEST_MAP_KEY)
from user_map.utilities.decorators import login_forbidden


def index(request):
    """Index page of user map.

    :param request: A django request object.
    :type request: request

    :returns: Response will be a nice looking map page.
    :rtype: HttpResponse
    """
    information_modal = loader.render_to_string(
        'user_map/information_modal.html')
    data_privacy_content = loader.render_to_string(
        'user_map/data_privacy.html')

    user_menu_button = loader.render_to_string(
        'user_map/user_menu_button.html', {'user': request.user})

    legend = loader.render_to_string(
        'user_map/legend.html', {'projects': PROJECTS})

    leaflet_tiles = dict(
        name=LEAFLET_TILES[0],
        url=LEAFLET_TILES[1],
        subdomains=LEAFLET_TILES[2],
        attribution=LEAFLET_TILES[3]
    )
    #
    # projects = [{
    #     'name': p['name'],
    #     'icon': do_static(p['icon']),
    #     'shadow_icon': do_static(p['shadow_icon']),
    #     'icon_size': p['icon_size']
    # } for p in PROJECTS]

    context = {
        'data_privacy_content': data_privacy_content,
        'information_modal': information_modal,
        'user_menu_button': user_menu_button,
        'projects': PROJECTS,
        'legend': legend,
        'leaflet_tiles': leaflet_tiles,
        'mapquest_key': MAPQUEST_MAP_KEY
    }
    return render(request, 'user_map/index.html', context)


def get_users(request):
    """Return a json document of users of the project.

    Users will belong to InaSAFE layer if they only have InaSAFE roles. If
    they have OSM role(s), they will belong to OSM layers.

    This will only fetch users who have approved the registration by email and
    still active.

    :param request: A django request object.
    :type request: request
    """

    if request.method == 'GET':

        # Get data:
        project = str(request.GET.get('project', ''))

        if project.lower() == 'inasafe':
            # only inasafe users
            users = User.objects.filter(
                is_confirmed=True,
                is_active=True,
                osm_roles=None).exclude(
                inasafe_roles=None).exclude(groups__name=REST_GROUP)
        elif project.lower() == 'openstreetmap':
            # only osm users
            users = User.objects.filter(
                is_confirmed=True,
                is_active=True,
                inasafe_roles=None).exclude(osm_roles=None).exclude(
                groups__name=REST_GROUP)
        else:
            # get users who have both roles
            users = User.objects.filter(
                is_confirmed=True, is_active=True).exclude(
                osm_roles=None).exclude(inasafe_roles=None).exclude(
                groups__name=REST_GROUP)

        context = {
            'users': users,
            'inasafe_cert_trainer_badge': INASAFE_CERTIFIED_TRAINER_BADGE,
            'osm_cert_trainer_badge': OSM_CERTIFIED_TRAINER_BADGE
        }
        users_json = loader.render_to_string(
            'user_map/users.json',
            context_instance=RequestContext(request, context))

        # Return Response
        return HttpResponse(users_json, content_type='application/json')
    else:
        raise Http404


@login_forbidden
def register(request):
    """User registration view.

    :param request: A django request object.
    :type request: request
    """
    if request.method == 'POST':
        form = RegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            form.save_m2m()

            current_site = get_current_site(request)
            domain = current_site.domain
            context = {
                'project_name': PROJECT_NAME,
                'protocol': 'http',
                'domain': domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'user_name': user.name,
                'key': user.key
            }
            email = loader.render_to_string(
                'user_map/account/registration_confirmation_email.html',
                context)

            subject = '%s User Registration' % PROJECT_NAME
            sender = '%s - No Reply <%s>' % (PROJECT_NAME, DEFAULT_FROM_MAIL)
            send_mail(
                subject, email, sender, [user.email], fail_silently=False)

            messages.success(
                request,
                ('Thank you for registering in our site! Please check your '
                 'email to confirm your registration'))
            return HttpResponseRedirect(reverse('user_map:register'))
    else:
        form = RegistrationForm()
    return render_to_response(
        'user_map/account/registration.html',
        {'form': form},
        context_instance=RequestContext(request)
    )


@login_forbidden
def confirm_registration(request, uid, key):
    """The view containing form to reset password and process it.

    :param request: A django request object.
    :type request: request

    :param uid: A unique id for a user.
    :type uid: str

    :param key: Key to confirm the user.
    :type key: str
    """
    decoded_uid = urlsafe_base64_decode(uid)
    try:
        user = User.objects.get(pk=decoded_uid)

        if not user.is_confirmed:
            if user.key == key:
                user.is_confirmed = True
                user.save(update_fields=['is_confirmed'])
                information = (
                    'Congratulations! Your account has been successfully '
                    'confirmed. Please continue to log in.')
            else:
                information = (
                    'Your link is not valid. Please make sure that you use '
                    'confirmation link we sent to your email.')
        else:
            information = ('Your account is already confirmed. Please '
                           'continue to log in.')
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        information = ('Your link is not valid. Please make sure that you use '
                       'confirmation link we sent to your email.')

    context = {
        'page_header_title': 'Registration Confirmation',
        'information': information
    }
    return render_to_response(
        'user_map/information.html',
        context,
        context_instance=RequestContext(request)
    )


@login_forbidden
def login(request):
    """Login view.

    :param request: A django request object.
    :type request: request
    """
    if request.method == 'POST':
        next_page = request.GET.get('next', '')
        if next_page == '':
            next_page = reverse('user_map:index')
        form = LoginForm(data=request.POST)
        if form.is_valid():
            user = authenticate(
                email=request.POST['email'],
                password=request.POST['password']
            )
            if user is not None:
                if user.is_active and user.is_confirmed:
                    django_login(request, user)

                    return HttpResponseRedirect(next_page)
                if not user.is_active:
                    errors = form._errors.setdefault(
                        NON_FIELD_ERRORS, ErrorList())
                    errors.append(
                        'The user is not active. Please contact our '
                        'administrator to resolve this.')
                if not user.is_confirmed:
                    errors = form._errors.setdefault(
                        NON_FIELD_ERRORS, ErrorList())
                    errors.append(
                        'Please confirm you registration email first!')
            else:
                errors = form._errors.setdefault(
                    NON_FIELD_ERRORS, ErrorList())
                errors.append(
                    'Please enter a correct email and password. '
                    'Note that both fields may be case-sensitive.')
    else:
        form = LoginForm()

    return render_to_response(
        'user_map/account/login.html',
        {'form': form},
        context_instance=RequestContext(request))


def logout(request):
    """Log out view.

    :param request: A django request object.
    :type request: request
    """
    django_logout(request)
    return HttpResponseRedirect(reverse('user_map:index'))


@login_required(login_url='user_map:login')
def update_user(request):
    """Update user view.

django_project/user_map/templates/user_map/account/edit_user.html
{% extends "user_map/base_page.html" %}
{% load leaflet_tags %}
{% load bootstrap %}

{% block head_resources %}
  {{ block.super }}
  {% leaflet_js plugins="forms" %}
  {% leaflet_css plugins="forms" %}
{% endblock head_resources %}

{% block main_content %}
  <div class="container">
    <div class="page-header">
    <h2>Update Profile
      <br><small>So I heard you want to update your information </small></h2>
    </div>

    <div class="update-provile-nav">
      <div class="col-md-2 well">
        <ul id="profile_tab" class="nav nav-stacked">
          <li>
            <a data-toggle="tab" href="#basic-information">Basic Information</a>
          </li>
          <li>
            <a data-toggle="tab" href="#security">Security</a>
          </li>
          <li>
            <a data-toggle="tab" href="#account-setting">Account Settings</a>
          </li>
        </ul>
      </div>
    </div>

    <div class="col-lg-9">
      <div id="profile_content" class="tab-content profile-content">
        {% if messages %}
          {% for message in messages %}
            {% if 'success' in message.tags %}
              <div class="alert alert-success">
                <a class="close" href="#" data-dismiss="alert">x</a>
                {{ message }}
              </div>
            {% endif %}
          {% endfor %}
        {% endif %}

        <div id="basic-information" class="tab-pane fade">
          <div class="panel panel-default">
             <div class="panel-heading">
               <h3 class="panel-title">Basic Information</h3>
             </div>
             <div class="panel-body">
               <form id="form-basic-info" class="form-horizontal" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ basic_info_form|bootstrap_horizontal:'col-lg-3'}}
                <div class="form-group">
                  <div class="col-lg-offset-3 col-lg-6">
                    <input type="submit" name="change_basic_info" value="Submit" class="btn btn-default">
                  </div>
                </div>
               </form>
             </div>
          </div>
        </div>

        <div id="security" class="tab-pane fade">
           <div class="panel panel-default">
             <div class="panel-heading">
               <h3 class="panel-title">Change Password</h3>
             </div>
             <div class="panel-body">
               <form id="form-security" class="form-horizontal" method="POST">
                 {% csrf_token %}
                 {{ change_password_form|bootstrap_horizontal:'col-lg-3'}}
                 <div class="form-group">
                   <div class="col-lg-offset-3 col-lg-6">
                     <input type="submit" name="change_password" value="Submit" class="btn btn-default">
                   </div>
                 </div>
               </form>
             </div>
           </div>
        </div>

        <div id="account-setting" class="tab-pane fade">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Delete Account</h3>
            </div>
            <div class="panel-body">
              <p>
                Once you delete your account, you will be no longer available
                on the map. However, you can register again any time you
                want!
              </p>
              <form method="POST" action="{% url 'user_map:delete_user' %}">
                {% csrf_token %}
                <input type="submit" value="Delete my account" class="btn btn-danger">
              </form>
            </div>
          </div>
        </div>
    </div>
  </div>
</div>
{% endblock main_content %}

{% block js_container %}
  <script type="text/javascript">
    $(document).on('shown.bs.tab', function(event) {
      var scrollmem = $('body').scrollTop();
      window.location.hash = $(event.target).attr('href');
      $('html,body').scrollTop(scrollmem);
    });

    $(document).ready(function () {
      var anchor_id = window.location.hash;
      if (anchor_id == "") {
        anchor_id = "{{ anchor_id }}"
      }
      $('#profile_tab a[href="'+ anchor_id +'"]').tab('show');
    });
  </script>
{% endblock js_container %}

django_project/user_map/templates/user_map/account/login.html
{% extends "user_map/base_page.html" %}
{% load leaflet_tags %}
{% load bootstrap %}

{% block head_resources %}
  {{ block.super }}
  {% leaflet_js plugins="forms" %}
  {% leaflet_css plugins="forms" %}
{% endblock head_resources %}

{% block main_content %}
   {{ block.super }}
  <div class="container autoheight">
    <div class="page-header">
    <h2>Sign In <br><small>Please provide your account information on the form
      below.</small></h2>
    </div>

    <div class="login-form">
      {% if messages %}
        {% for message in messages %}
          {% if 'success' in message.tags %}
            <div class="alert alert-success">
              <a class="close" href="#" data-dismiss="alert">x</a>
              {{ message }}
            </div>
          {% endif %}
        {% endfor %}
      {% endif %}

      <form class="form-horizontal" action='#' method='POST'>
        {% csrf_token %}
        {{ form|bootstrap_horizontal:'col-lg-3'}}
        <div class="form-group">
          <div class="col-lg-offset-3 col-lg-4">
            <input type="submit" value="Sign In" class="btn btn-default">
          </div>
        </div>
        <div class="form-group">
        <div class="col-lg-offset-3 col-lg-6">
          <a href="{% url 'user_map:password_reset'%}">Forgot your password?</a>
        </div>
      </div>
      </form>
    </div>
  </div>
{% endblock main_content %}

{% block js_container %}
  {{ block.super }}
{% endblock js_container %}

django_project/user_map/templates/user_map/account/password_reset_complete.html
{% extends 'user_map/base_page.html' %}

{% block main_content %}
  <div class="container autoheight">
    <div class="main-content">
      <div class="page-header">
      <h2>Reset Password Complete</h2>
      </div>
    </div>

    <p>Your password has been reset.  You may go ahead and log in now.</p>
    <p><a href="{% url 'user_map:login' %}">Log in</a></p>

  </div>
{% endblock main_content%}

django_project/user_map/templates/user_map/account/password_reset_confirm.html
{% extends 'user_map/base_page.html' %}
{% load bootstrap %}

{% block title %}Reset Password{% endblock %}

{% block main_content %}
  <div class="container autoheight">
    <div class="main-content">
      <div class="page-header">
      <h2>Reset Your Password
        <br><small>Please enter your new password on the form below.</small></h2>
      </div>
    </div>

    {% if validlink %}
      <div class="set-new-password-form">
        <form class="form-horizontal" action='#' method='POST'>
          {% csrf_token %}
          {{ form|bootstrap_horizontal:'col-lg-3'}}
          <div class="form-group">
            <div class="col-lg-offset-3 col-lg-3">
              <input type="submit" value="Submit" class="btn btn-default">
            </div>
          </div>
        </form>
      </div>
    {% else %}
      <p>Ooops! This reset link is no longer valid!</p>
    {% endif %}
  </div>
{% endblock main_content %}

django_project/user_map/templates/user_map/account/password_reset_done.html
{% extends 'user_map/base_page.html' %}

{% block main_content %}
  <div class="container autoheight">
    <div class="main-content">
      <div class="page-header">
      <h2>Reset Password</h2>
      </div>
    </div>

    <p>We've e-mailed you instructions for setting your password to the e-mail address you submitted.</p>
    <p>You should be receiving it shortly.</p>
    <br>
    <p>
      If you don't receive an email, please make sure you've entered the
      address you registered with, and check your spam folder.
    </p>
  </div>
{% endblock main_content%}

django_project/user_map/templates/user_map/account/password_reset_email.html
{% autoescape off %}
Hi {{ user.name}},

You're receiving this email because you requested a password reset for your user account at {{ site_name }}
Please go to the following page to set a new password:
{{ protocol}}://{{ domain }}{% url 'user_map:password_reset_confirm' uidb64=uid token=token %}

Thanks for using our site!
{% endautoescape %}

django_project/user_map/templates/user_map/account/password_reset_form.html
{% extends 'user_map/base_page.html' %}
{% load bootstrap %}

{% block title %}Reset Password {% endblock %}

{% block main_content %}
  <div class="container autoheight">
    <div class="main-content">
      <div class="page-header">
      <h2>Reset Password <br><small>Please provide your account information
        on the form below.</small></h2>
      </div>
    </div>

    <div class="ask-password-reset-form">
      <form class="form-horizontal" action='#' method='POST'>
      {% csrf_token %}
      {{ form|bootstrap_horizontal:'col-lg-2'}}
      <div class="form-group">
        <div class="col-lg-offset-2 col-lg-4">
          <input type="submit" value="Submit" class="btn btn-default">
        </div>
      </div>
    </form>
    </div>
  </div>
{% endblock main_content %}

django_project/user_map/templates/user_map/account/registration.html
{% extends "user_map/base_page.html" %}
{% load leaflet_tags %}
{% load bootstrap %}

{% block head_resources %}
  {{ block.super }}
  {% leaflet_js plugins="forms" %}
  {% leaflet_css plugins="forms" %}
{% endblock head_resources %}

{% block main_content %}
  <div class="container">
    <div class="page-header">
    <h2>Add me to the map! <br><small>Please provide your information on the
      form
      below.</small></h2>
    </div>
    <div class="registration-form">
      {% if messages %}
        {% for message in messages %}
          {% if 'success' in message.tags %}
            <div class="alert alert-success">
              <a class="close" href="#" data-dismiss="alert">x</a>
              {{ message }}
            </div>
          {% endif %}
        {% endfor %}
      {% endif %}
      <form class="form-horizontal" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|bootstrap_horizontal:'col-lg-3'}}
        <div class="form-group">
          <div class="col-lg-offset-3 col-lg-4">
            <input type="submit" value="Submit" class="btn btn-default">
          </div>
        </div>
      </form>
     </div>
  </div>
{% endblock main_content %}

{% block js_container %}
  <script type="text/javascript">
    var $osm_roles_checkboxes = $('input[name="osm_roles"]');
    var $osm_username = $('input[name="osm_username"]');
    showOSMInput();

    $osm_roles_checkboxes.click(function() {
      showOSMInput();
    });

    function showOSMInput() {
      var $osm_roles = $('input[name="osm_roles"]:checked');
      if ($osm_roles.length > 0) {
        $osm_username.parent().parent().show('fast');
      } else {
        $osm_username.parent().parent().hide('fast');
      }
    }
  </script>
{% endblock js_container %}

django_project/user_map/templates/user_map/account/registration_confirmation_email.html
Dear {{ user_name }},

Thank you for adding yourself to the {{ project_name }} User Map. To activate
your account, please click this link:
{{ protocol}}://{{ domain }}{% url 'user_map:confirm_registration' uid=uid key=key %}

Please note that the following information in your user record will be freely downloadable
and can be obtained by anyone visiting the user map page:
    - Your name
    - your location (longitude, latitude)
    - your photo
    - your InaSAFE role (user, developer, trainer, or certified trainer)
    - your OSM role (mapper, trainer, or certified trainer)
    - your OSM Username

If you are concerned about your privacy, we recommend you edit your record (you can
do so using the link provided below) and generalise the position of your point (for example
to the centre of your nearest town / state or province or country).

Thank you for taking the time to register yourself on our site!

Regards,
The {{ project_name }} Team