django_project/core/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from django.views.i18n import javascript_catalog
from realtime.admin import realtime_admin_site


js_info_dict = {
    'packages': ('realtime',),
}

urlpatterns = patterns(
    '',

    url(r'^admin/', include(admin.site.urls)),

    # uncomment to enable defaut Django auth
    # url(r'^accounts/login/$', 'django.contrib.auth.views.login'),

    # include application urls
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'', include('frontend.urls', namespace='front_end')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^mce_filebrowser/', include('mce_filebrowser.urls')),
    url(r'^user-map/', include('user_map.urls', namespace='user_map')),
    url(r'^jsi18n/$', javascript_catalog, js_info_dict),
    url(r'^realtime/', include('realtime.urls', namespace='realtime')),
    url(r'^realtime/api-auth/', include(
        'rest_framework.urls', namespace='rest_framework')),
    # alias for auth in realtime
    url(r'^realtime/api/v1/auth/', include(
        'rest_framework.urls', namespace='rest_framework')),
    url(r'^realtime/admin/', include(realtime_admin_site.urls)),

    # url pattern for realtime reports
    url(r'', include('realtime.report_urls', namespace='realtime_report')),

    # url pattern for realtime flatpages
    # not appending slash because flatpages url starts with one
    url(r'^realtime/pages', include('django.contrib.flatpages.urls')),
)

# expose static files and uploded media if DEBUG is active
if settings.DEBUG:
    urlpatterns += patterns(
        '',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {
                'document_root': settings.MEDIA_ROOT,
                'show_indexes': True
            }),
        url(r'', include('django.contrib.staticfiles.urls'))
    )
else:
    # for production mode
    # Although it will also be served by nginx
    # Useful for testing production environment in local configuration
    urlpatterns += patterns(
        '',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {
                'document_root': settings.MEDIA_ROOT,
                'show_indexes': False
            }),
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
            {
                'document_root': settings.STATIC_ROOT,
                'show_indexes': False
            }),
    )

django_project/realtime/urls.py
# coding=utf-8
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns

from realtime.views import user_push, root
from realtime.views.ash import (
    index as ash_index,
    upload_form as ash_upload_form, AshList, AshReportList, AshReportDetail,
    AshDetail, AshFeatureList, ash_report_map)
from realtime.views.earthquake import (
    index as shake_index,
    EarthquakeList,
    EarthquakeDetail,
    EarthquakeReportList,
    EarthquakeReportDetail,
    EarthquakeFeatureList, iframe_index, get_grid_xml)
from realtime.views.flood import (
    index as flood_index,
    FloodList,
    FloodDetail,
    FloodReportList,
    FloodReportDetail, FloodEventList, flood_event_features,
    impact_event_features, rw_flood_frequency, rw_histogram,
    flood_impact_report, flood_impact_map)
from realtime.views.reports import latest_report
from realtime.views.volcano import VolcanoFeatureList, VolcanoList

urlpatterns = [
    url(r'^api/v1/$', root.api_root, name='api_root'),

    # Earthquake
    url(r'^api/v1/earthquake/$',
        EarthquakeList.as_view(),
        name='earthquake_list'),
    url(r'^api/v1/earthquake-feature/$',
        EarthquakeFeatureList.as_view(),
        name='earthquake_feature_list'),
    url(r'^api/v1/earthquake/(?P<shake_id>[-\w]+)/$',
        EarthquakeDetail.as_view(),
        name='earthquake_detail'),
    url(r'^api/v1/earthquake-report/$',
        EarthquakeReportList.as_view(),
        name='earthquake_report_list'),
    url(r'^api/v1/earthquake-report/'
        r'(?P<shake_id>[-\d]+)/$',
        EarthquakeReportList.as_view(),
        name='earthquake_report_list'),
    url(r'^api/v1/earthquake-report/'
        r'(?P<shake_id>[-\d]+)/'
        r'(?P<language>[-\w]+)/$',
        EarthquakeReportDetail.as_view(),
        name='earthquake_report_detail'),

    # Flood
    url(r'^api/v1/flood/$',
        FloodList.as_view(),
        name='flood_list'),
    url(r'^api/v1/flood-events/$',
        FloodEventList.as_view(),
        name='flood_event_list'),
    url(r'^api/v1/flood-event-features/'
        r'(?P<event_id>\d{10}-(1|3|6)-(rw|village|subdistrict))/$',
        flood_event_features,
        name='flood_event_features'),
    url(r'^api/v1/flood-impact-event-features/'
        r'(?P<event_id>\d{10}-(1|3|6)-(rw|village|subdistrict))/$',
        impact_event_features,
        name='flood_impact_event_features'),
    url(r'^api/v1/flood/'
        r'(?P<event_id>\d{10}-(1|3|6)-(rw|village|subdistrict))/$',
        FloodDetail.as_view(),
        name='flood_detail'),
    url(r'^api/v1/flood-report/$',
        FloodReportList.as_view(),
        name='flood_report_list'),
    url(r'^api/v1/flood-report/'
        r'(?P<event_id>\d{10}-(1|3|6)-(rw|village|subdistrict))/$',
        FloodReportList.as_view(),
        name='flood_report_list'),
    url(r'^api/v1/flood-report/'
        r'(?P<event_id>\d{10}-(1|3|6)-(rw|village|subdistrict))/'
        r'(?P<language>[-\w]+)/$',
        FloodReportDetail.as_view(),
        name='flood_report_detail'),

    # Volcano
    url(r'^api/v1/volcano-feature/$',
        VolcanoFeatureList.as_view(),
        name='volcano_feature_list'),
    url(r'^api/v1/volcano-list/$',
        VolcanoList.as_view(),
        name='volcano_list'),

    # Ash
    url(r'^api/v1/ash/$',
        AshList.as_view(),
        name='ash_list'),
    url(r'^api/v1/ash-report/$',
        AshReportList.as_view(),
        name='ash_report_list'),
    url(r'^api/v1/ash/'
        r'(?P<volcano_name>[\w -]+)/'
        r'(?P<event_time>[\d+-]{19})/$',
        AshDetail.as_view(),
        name='ash_detail'),
    url(r'^api/v1/ash-report/'
        r'(?P<volcano_name>[\w -]+)/$',
        AshReportList.as_view(),
        name='ash_report_list'),
    url(r'^api/v1/ash-report/'
        r'(?P<volcano_name>[\w -]+)/'
        r'(?P<event_time>[\d+-]{19})/$',
        AshReportList.as_view(),
        name='ash_report_list'),
    url(r'^api/v1/ash-report/'
        r'(?P<volcano_name>[\w -]+)/'
        r'(?P<event_time>[\d+-]{19})/'
        r'(?P<language>[-\w]+)/$',
        AshReportDetail.as_view(),
        name='ash_report_detail'),
    url(r'^api/v1/ash-feature/$',
        AshFeatureList.as_view(),
        name='ash_feature_list'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

urlpatterns += [
    url(r'^$', shake_index, name='index'),

    # SHake
    url(r'^shake/$', shake_index, name='shake_index'),
    url(r'^shake/grid/(?P<shake_id>[-\d]+)', get_grid_xml, name='shake_grid'),

    # Flood
    url(r'^flood/$', flood_index, name='flood_index'),
    url(r'^flood/impact-report/'
        r'(?P<event_id>\d{10}-(1|3|6)-(rw|village|subdistrict))/'
        r'(?P<language>[-\w]+)/$',
        flood_impact_report,
        name='flood_impact_report'),
    url(r'^flood/impact-map/'
        r'(?P<event_id>\d{10}-(1|3|6)-(rw|village|subdistrict))/'
        r'(?P<language>[-\w]+)/$',
        flood_impact_map,
        name='flood_impact_map'),

    # Ash
    url(r'^ash/$', ash_index, name='ash_index'),
    url(r'^ash/upload$', ash_upload_form, name='ash_upload_form'),
    url(r'^ash/report-map/'
        r'(?P<volcano_name>[\w -]+)/'
        r'(?P<event_time>[\d+-]{19})/'
        r'(?P<language>[-\w]+)/$',
        ash_report_map,
        name='ash_report_map'),

    # IFrame
    url(r'^iframe$', iframe_index, name='iframe'),
    url(r'^api/v1/is_logged_in/$', root.is_logged_in),
    url(r'^api/v1/indicator/notify_shakemap_push/$',
        user_push.notify_shakemap_push),
    url(r'^indicator$', user_push.indicator, name='indicator'),
    url(r'^indicator/rest_users$',
        user_push.realtime_rest_users,
        name='rest_users'),
    url(r'^latest_report/'
        r'(?P<report_type>(pdf|png|thumbnail))/'
        r'(?P<language>\w*)/?$',
        latest_report,
        name='latest_report'),
    url(r'^rw-flood-frequency/(?P<hazard_levels_string>[\d,]*)',
        rw_flood_frequency,
        name='rw_flood_frequency'),
    url(r'^rw-histogram/'
        r'(?P<boundary_id>\w+)/'
        r'(?P<hazard_levels_string>[\d,]*)/'
        r'(?P<start_date_timestamp>[\w-]*)/'
        r'(?P<end_date_timestamp>[\w-]*)',
        rw_histogram,
        name='rw_histogram'),
]

django_project/realtime/forms/coreflatpage.py
# coding=utf-8

from django import forms
from realtime.models.coreflatpage import CoreFlatPage
from tinymce.widgets import TinyMCE

__author__ = 'Rizky Maulana Nugraha <lana.pcfre@gmail.com>'


class CoreFlatPageForm(forms.ModelForm):
    """Override form to allow tinyMCE for content field"""

    content = forms.CharField(
        widget=TinyMCE(
            attrs={
                'cols': 80,
                'rows': 30,

            }
        )
    )

    class Meta:
        model = CoreFlatPage
        fields = '__all__'

django_project/realtime/views/reports.py
# coding=utf-8
import os
from django.conf import settings
from django.http.response import HttpResponse, Http404
from realtime.models.earthquake import EarthquakeReport

__author__ = 'Rizky Maulana Nugraha "lucernae" <lana.pcfre@gmail.com>'
__date__ = '19/06/15'


def report_pdf(request, shake_id, language=u'id', language2=u'id'):
    """Return PDF file of desired shake id and language

    :param request: Django request object
    :param shake_id: Shake ID
    :param language: Language of the report
    :param language2: Language of the report, only a dummy variable, because
        of URL pattern
    :return: PDF file
    """
    try:
        report = EarthquakeReport.objects.get(
            earthquake__shake_id=shake_id,
            language=language)
        if not language == language2:
            raise Http404()
        response = HttpResponse(
            report.report_pdf.read(), content_type='application/octet-stream')
        response['Content-Disposition'] = 'inline; filename="%s-%s.pdf";' % (
            shake_id, language)
        return response
    except IOError:
        raise Http404()
    except EarthquakeReport.DoesNotExist:
        # if it doesn't exists in the database. Try to get it directly from
        # media folder
        filename = '%s-%s.pdf' % (shake_id, language)
        filename = os.path.join(
            settings.MEDIA_ROOT, 'reports/pdf/%s' % filename)
        try:
            with open(filename) as f:
                response = HttpResponse(
                    f.read(),
                    content_type='application/octet-stream')
                response['Content-Disposition'] = 'inline; filename="%s";' % (
                    filename, )
                return response
        except IOError:
            raise Http404()


def report_image(request, shake_id, language=u'id', language2=u'id'):
    """Return PNG file of desired shake id and language

    :param request: Django request object
    :param shake_id: Shake ID
    :param language: Language of the report
    :param language2: Language of the report, only a dummy variable, because
        of URL pattern
    :return: PNG file
    """
    try:
        report = EarthquakeReport.objects.get(
            earthquake__shake_id=shake_id,
            language=language)
        if not language == language2:
            raise Http404()
        response = HttpResponse(
            report.report_image.read(),
            content_type='application/octet-stream')
        response['Content-Disposition'] = 'inline; filename="%s-%s.png";' % (
            shake_id, language)
        return response
    except IOError:
        raise Http404()
    except EarthquakeReport.DoesNotExist:
        # if it doesn't exists in the database. Try to get it directly from
        # media folder
        filename = '%s-%s.png' % (shake_id, language)
        filename = os.path.join(
            settings.MEDIA_ROOT, 'reports/png/%s' % filename)
        try:
            with open(filename) as f:
                response = HttpResponse(
                    f.read(),
                    content_type='application/octet-stream')
                response['Content-Disposition'] = 'inline; filename="%s";' % (
                    filename, )
                return response
        except IOError:
            raise Http404()


def report_thumbnail(request, shake_id, language=u'id', language2=u'id'):
    """Return Thumbnail file of desired shake id and language

    Thumbnail file is a smaller-downsized version of Image report

    :param request: Django request object
    :param shake_id: Shake ID
    :param language: Language of the report
    :param language2: Language of the report, only a dummy variable, because
        of URL pattern
    :return: Thumbnail file
    """
    try:
        report = EarthquakeReport.objects.get(
            earthquake__shake_id=shake_id,
            language=language)
        if not language == language2:
            raise Http404()
        response = HttpResponse(
            report.report_thumbnail.read(),
            content_type='application/octet-stream')
        response['Content-Disposition'] = 'inline; filename="%s-%s.png";' % (
            shake_id, language)
        return response
    except IOError:
        raise Http404()
    except EarthquakeReport.DoesNotExist:
        # if it doesn't exists in the database. Try to get it directly from
        # media folder
        filename = '%s-thumb-%s.png' % (shake_id, language)
        filename = os.path.join(
            settings.MEDIA_ROOT, 'reports/png/%s' % filename)
        try:
            with open(filename) as f:
                response = HttpResponse(
                    f, content_type='application/octet-stream')
                response['Content-Disposition'] = 'inline; filename="%s";' % (
                    filename, )
                return response
        except IOError:
            raise Http404()


def latest_report(request, report_type=u'pdf', language=u'id'):
    """Return the latest report file of desired report type and language

    :param request: Django request object
    :param report_type: Report type, can be 'pdf', 'png', or 'thumbnail'
    :param language: Language of the report
    :return: Desired report file
    """
    try:
        report = EarthquakeReport.objects.filter(
            language=language).order_by('earthquake__shake_id').last()

        if not report:
            raise Http404()

        if report_type == 'pdf':
            report_pdf(
                request, report.earthquake.shake_id, language, language)
        elif report_type == 'png':
            report_image(
                request, report.earthquake.shake_id, language, language)
        elif report_type == 'thumbnail':
            report_thumbnail(
                request, report.earthquake.shake_id, language, language)

        raise Http404()
    except (EarthquakeReport.DoesNotExist, IOError, AttributeError):
        raise Http404()

django_project/realtime/views/root.py
# coding=utf-8
from django.http.response import JsonResponse
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.reverse import reverse

__author__ = 'Rizky Maulana Nugraha "lucernae" <lana.pcfre@gmail.com>'
__date__ = '24/06/15'


@api_view(('GET',))
def api_root(request, format=None, **kwargs):
    kwargs['request'] = request
    kwargs['format'] = format
    return Response({
        'model_list': {
            'earthquakes': reverse('realtime:earthquake_list', **kwargs),
            'earthquake-reports': reverse(
                'realtime:earthquake_report_list', **kwargs),
            'earthquake-feature-list': reverse(
                'realtime:earthquake_feature_list', **kwargs),
            'floods': reverse('realtime:flood_list', **kwargs),
            'volcanos': reverse('realtime:volcano_list', **kwargs),
            'volcano-feature-list': reverse(
                'realtime:volcano_feature_list', **kwargs),
            'ash': reverse('realtime:ash_list', **kwargs),
            'ash-report': reverse('realtime:ash_report_list', **kwargs),
        }
    })


def is_logged_in(request):
    data = {
        'is_logged_in': request.user.is_authenticated()
    }
    return JsonResponse(data=data)

django_project/realtime/views/volcano.py
# coding=utf-8
from rest_framework import mixins
from rest_framework.filters import DjangoFilterBackend, SearchFilter, \
    OrderingFilter
from rest_framework.generics import GenericAPIView
from rest_framework.permissions import DjangoModelPermissionsOrAnonReadOnly

from realtime.models.volcano import Volcano
from realtime.serializers.volcano_serializer import VolcanoGeoJsonSerializer, \
    VolcanoSerializer

__author__ = 'Rizky Maulana Nugraha <lana.pcfre@gmail.com>'
__date__ = '7/18/16'


class VolcanoList(mixins.ListModelMixin, GenericAPIView):
    queryset = Volcano.objects.all()
    serializer_class = VolcanoSerializer
    filter_backends = (DjangoFilterBackend, SearchFilter, OrderingFilter)
    # filter_fields = ('volcano_name', 'morphology', 'region', 'subregion')
    # filter_class = VolcanoFilter
    search_fields = ('volcano_name', )
    ordering = ('volcano_name', )
    permission_classes = (DjangoModelPermissionsOrAnonReadOnly, )

    def get(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)


class VolcanoFeatureList(VolcanoList):
    serializer_class = VolcanoGeoJsonSerializer
    pagination_class = None

django_project/realtime/templates/realtime/indicator.html
{% extends "realtime/base.html" %}
{% load staticfiles %}
{% load leaflet_tags %}
{% load bootstrap %}
{% load pipeline %}
{% load humanize %}
{% load i18n %}
{% load realtime_extras %}

{% block head_resources %}
    {{ block.super }}
    {% leaflet_js %}
    {% leaflet_css %}
    <!--[if lte IE 8]>
    <link rel="stylesheet" href="{% static 'realtime/css/MarkerCluster.user-map.ie.css' %}" />
    <![endif]-->
    {% stylesheet 'realtime_contrib' %}
    {% stylesheet 'realtime_appcss' %}
    {% stylesheet 'main' %}
    {% javascript 'realtime_contrib' %}
    {% javascript 'realtime_templates' %}
    {% javascript 'realtime_appjs' %}
    {{ form.media }}
{% endblock head_resources %}

{% block main_content %}
    <div class="row center-block">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h2 class="panel-title">Realtime REST Users</h2>
            </div>
            <div class="panel-body">
                <table class="table table-striped table-bordered table-hover" id="realtime-rest-users">
                    <thead>
                        <tr>
                            <th data-dynatable-column="username">{% trans "Username" %}</th>
                            <th data-dynatable-column="email">{% trans "Email" %}</th>
                            <th data-dynatable-column="last_shakemap_push">{% trans "Last Shakemap Push" %}</th>
                            <th data-dynatable-column="last_rest_push">{% trans "Last REST Push" %}</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div class="row center-block">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h2 class="panel-title">Realtime Indicator</h2>
            </div>
            <div class="panel-body">
                <table class="table table-striped table-condensed table-hover" id="realtime-indicator">
                    <thead>
                        <tr>
                            <th>{% trans "Indicator" %}</th>
                            <th>{% trans "Value" %}</th>
                            <th>{% trans "Status" %}</th>
                            <th>{% trans "Notes" %}</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for indicator in indicators %}
                        <tr>
                            <td>{{ indicator.label }}</td>
                            <td>{{ indicator.value_humanize }}</td>
                            <td>
                                <span class="label label-{{ indicator|indicator_bootstrap_class }}">
                                    <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span>
                                    {{ indicator.status_text|safe }}
                                </span>
                            </td>
                            <td>
                                {{ indicator.notes|safe }}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block js_container %}
    <script type="text/javascript">
        $(document).ready(function(){
            var dynaTable = $('#realtime-rest-users').dynatable({
                table: {
                    defaultColumnIdStyle: 'underscore',
                },
                dataset: {
                    records: [],
                    sorts: {'username': -1}
                }
            }).data('dynatable');

            var get_users_url = '{% url 'realtime:rest_users' %}'
            $.get(get_users_url, function(data){
                dynaTable.settings.dataset.originalRecords = data.users;
                dynaTable.paginationPerPage.set(100);
                dynaTable.sorts.add('username', -1);
                dynaTable.process();
            });
        });
    </script>
{% endblock %}

django_project/realtime/templates/realtime/nav_second.html
{% load i18n %}

<nav class="nav-second navbar-collapse collapse">
    <ul class="menu">
        <li class="menu-item">
            <a href="{% url 'realtime:shake_index' %}">{% trans "Earthquake" %}</a>
        </li>
        <li class="menu-item">
            <a href="{% url 'realtime:flood_index' %}">{% trans "Flood" %}</a>
        </li>
        {% if ASH_SHOW_PAGE %}
        <li class="menu-item">
            <a href="{% url 'realtime:ash_index' %}">{% trans "Volcanic Ash" %}</a>
        </li>
        {% endif %}
        <li class="menu-item">
            <a href="{% url 'realtime:api_root' %}">{% trans "API Browser" %}</a>
        </li>
        <li class="menu-item">
            <a href="{% url 'realtime:indicator' %}">{% trans "Indicator" %}</a>
        </li>
        {% for g in flatpages.groups %}
            {% with pages=g.pages %}
                {% if pages %}
                <li class="menu-item dropdown">
                    <a href="#" class="dropdown-toggle" title="{{ g.title|capfirst }}" data-toggle="dropdown" class="dropdown-toggle" aria-haspopup="true" aria-expanded="true">
                        {{ g.title|capfirst }}
                        <span class="caret"></span>
                    </a>
                    <ul role="menu" class="dropdown-menu">
                        {% for p in pages %}
                            <li class="menu-item">
                                <a title="{{ p.title }}"
                                   href="{% url 'django.contrib.flatpages.views.flatpage' url=p.url %}">
                                    {{ p.title|capfirst }}
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </li>
                {% endif %}
            {% endwith %}
        {% endfor %}
    </ul>
</nav>