django_project/core/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from django.views.i18n import javascript_catalog
from realtime.admin import realtime_admin_site


js_info_dict = {
    'packages': ('realtime',),
}

urlpatterns = patterns(
    '',

    url(r'^admin/', include(admin.site.urls)),

    # uncomment to enable defaut Django auth
    # url(r'^accounts/login/$', 'django.contrib.auth.views.login'),

    # include application urls
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'', include('frontend.urls', namespace='front_end')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^mce_filebrowser/', include('mce_filebrowser.urls')),
    url(r'^user-map/', include('user_map.urls', namespace='user_map')),
    url(r'^jsi18n/$', javascript_catalog, js_info_dict),
    url(r'^realtime/', include('realtime.urls', namespace='realtime')),
    url(r'^realtime/api-auth/', include(
        'rest_framework.urls', namespace='rest_framework')),
    # alias for auth in realtime
    url(r'^realtime/api/v1/auth/', include(
        'rest_framework.urls', namespace='rest_framework')),
    url(r'^realtime/admin/', include(realtime_admin_site.urls)),

    # url pattern for realtime reports
    url(r'', include('realtime.report_urls', namespace='realtime_report')),

    # url pattern for realtime flatpages
    # not appending slash because flatpages url starts with one
    url(r'^realtime/pages', include('django.contrib.flatpages.urls')),
)

# expose static files and uploded media if DEBUG is active
if settings.DEBUG:
    urlpatterns += patterns(
        '',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {
                'document_root': settings.MEDIA_ROOT,
                'show_indexes': True
            }),
        url(r'', include('django.contrib.staticfiles.urls'))
    )
else:
    # for production mode
    # Although it will also be served by nginx
    # Useful for testing production environment in local configuration
    urlpatterns += patterns(
        '',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {
                'document_root': settings.MEDIA_ROOT,
                'show_indexes': False
            }),
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
            {
                'document_root': settings.STATIC_ROOT,
                'show_indexes': False
            }),
    )

django_project/realtime/urls.py
# coding=utf-8
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns

from realtime.views import user_push, root
from realtime.views.ash import (
    index as ash_index,
    upload_form as ash_upload_form, AshList, AshReportList, AshReportDetail,
    AshDetail, AshFeatureList, ash_report_map)
from realtime.views.earthquake import (
    index as shake_index,
    EarthquakeList,
    EarthquakeDetail,
    EarthquakeReportList,
    EarthquakeReportDetail,
    EarthquakeFeatureList, iframe_index, get_grid_xml)
from realtime.views.flood import (
    index as flood_index,
    FloodList,
    FloodDetail,
    FloodReportList,
    FloodReportDetail, FloodEventList, flood_event_features,
    impact_event_features, rw_flood_frequency, rw_histogram,
    flood_impact_report, flood_impact_map)
from realtime.views.reports import latest_report
from realtime.views.volcano import VolcanoFeatureList, VolcanoList

urlpatterns = [
    url(r'^api/v1/$', root.api_root, name='api_root'),

    # Earthquake
    url(r'^api/v1/earthquake/$',
        EarthquakeList.as_view(),
        name='earthquake_list'),
    url(r'^api/v1/earthquake-feature/$',
        EarthquakeFeatureList.as_view(),
        name='earthquake_feature_list'),
    url(r'^api/v1/earthquake/(?P<shake_id>[-\w]+)/$',
        EarthquakeDetail.as_view(),
        name='earthquake_detail'),
    url(r'^api/v1/earthquake-report/$',
        EarthquakeReportList.as_view(),
        name='earthquake_report_list'),
    url(r'^api/v1/earthquake-report/'
        r'(?P<shake_id>[-\d]+)/$',
        EarthquakeReportList.as_view(),
        name='earthquake_report_list'),
    url(r'^api/v1/earthquake-report/'
        r'(?P<shake_id>[-\d]+)/'
        r'(?P<language>[-\w]+)/$',
        EarthquakeReportDetail.as_view(),
        name='earthquake_report_detail'),

    # Flood
    url(r'^api/v1/flood/$',
        FloodList.as_view(),
        name='flood_list'),
    url(r'^api/v1/flood-events/$',
        FloodEventList.as_view(),
        name='flood_event_list'),
    url(r'^api/v1/flood-event-features/'
        r'(?P<event_id>\d{10}-(1|3|6)-(rw|village|subdistrict))/$',
        flood_event_features,
        name='flood_event_features'),
    url(r'^api/v1/flood-impact-event-features/'
        r'(?P<event_id>\d{10}-(1|3|6)-(rw|village|subdistrict))/$',
        impact_event_features,
        name='flood_impact_event_features'),
    url(r'^api/v1/flood/'
        r'(?P<event_id>\d{10}-(1|3|6)-(rw|village|subdistrict))/$',
        FloodDetail.as_view(),
        name='flood_detail'),
    url(r'^api/v1/flood-report/$',
        FloodReportList.as_view(),
        name='flood_report_list'),
    url(r'^api/v1/flood-report/'
        r'(?P<event_id>\d{10}-(1|3|6)-(rw|village|subdistrict))/$',
        FloodReportList.as_view(),
        name='flood_report_list'),
    url(r'^api/v1/flood-report/'
        r'(?P<event_id>\d{10}-(1|3|6)-(rw|village|subdistrict))/'
        r'(?P<language>[-\w]+)/$',
        FloodReportDetail.as_view(),
        name='flood_report_detail'),

    # Volcano
    url(r'^api/v1/volcano-feature/$',
        VolcanoFeatureList.as_view(),
        name='volcano_feature_list'),
    url(r'^api/v1/volcano-list/$',
        VolcanoList.as_view(),
        name='volcano_list'),

    # Ash
    url(r'^api/v1/ash/$',
        AshList.as_view(),
        name='ash_list'),
    url(r'^api/v1/ash-report/$',
        AshReportList.as_view(),
        name='ash_report_list'),
    url(r'^api/v1/ash/'
        r'(?P<volcano_name>[\w -]+)/'
        r'(?P<event_time>[\d+-]{19})/$',
        AshDetail.as_view(),
        name='ash_detail'),
    url(r'^api/v1/ash-report/'
        r'(?P<volcano_name>[\w -]+)/$',
        AshReportList.as_view(),
        name='ash_report_list'),
    url(r'^api/v1/ash-report/'
        r'(?P<volcano_name>[\w -]+)/'
        r'(?P<event_time>[\d+-]{19})/$',
        AshReportList.as_view(),
        name='ash_report_list'),
    url(r'^api/v1/ash-report/'
        r'(?P<volcano_name>[\w -]+)/'
        r'(?P<event_time>[\d+-]{19})/'
        r'(?P<language>[-\w]+)/$',
        AshReportDetail.as_view(),
        name='ash_report_detail'),
    url(r'^api/v1/ash-feature/$',
        AshFeatureList.as_view(),
        name='ash_feature_list'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

urlpatterns += [
    url(r'^$', shake_index, name='index'),

    # SHake
    url(r'^shake/$', shake_index, name='shake_index'),
    url(r'^shake/grid/(?P<shake_id>[-\d]+)', get_grid_xml, name='shake_grid'),

    # Flood
    url(r'^flood/$', flood_index, name='flood_index'),
    url(r'^flood/impact-report/'
        r'(?P<event_id>\d{10}-(1|3|6)-(rw|village|subdistrict))/'
        r'(?P<language>[-\w]+)/$',
        flood_impact_report,
        name='flood_impact_report'),
    url(r'^flood/impact-map/'
        r'(?P<event_id>\d{10}-(1|3|6)-(rw|village|subdistrict))/'
        r'(?P<language>[-\w]+)/$',
        flood_impact_map,
        name='flood_impact_map'),

    # Ash
    url(r'^ash/$', ash_index, name='ash_index'),
    url(r'^ash/upload$', ash_upload_form, name='ash_upload_form'),
    url(r'^ash/report-map/'
        r'(?P<volcano_name>[\w -]+)/'
        r'(?P<event_time>[\d+-]{19})/'
        r'(?P<language>[-\w]+)/$',
        ash_report_map,
        name='ash_report_map'),

    # IFrame
    url(r'^iframe$', iframe_index, name='iframe'),
    url(r'^api/v1/is_logged_in/$', root.is_logged_in),
    url(r'^api/v1/indicator/notify_shakemap_push/$',
        user_push.notify_shakemap_push),
    url(r'^indicator$', user_push.indicator, name='indicator'),
    url(r'^indicator/rest_users$',
        user_push.realtime_rest_users,
        name='rest_users'),
    url(r'^latest_report/'
        r'(?P<report_type>(pdf|png|thumbnail))/'
        r'(?P<language>\w*)/?$',
        latest_report,
        name='latest_report'),
    url(r'^rw-flood-frequency/(?P<hazard_levels_string>[\d,]*)',
        rw_flood_frequency,
        name='rw_flood_frequency'),
    url(r'^rw-histogram/'
        r'(?P<boundary_id>\w+)/'
        r'(?P<hazard_levels_string>[\d,]*)/'
        r'(?P<start_date_timestamp>[\w-]*)/'
        r'(?P<end_date_timestamp>[\w-]*)',
        rw_histogram,
        name='rw_histogram'),
]

django_project/realtime/models/ash.py
# coding=utf-8
"""Model class for ash realtime."""
import pytz
from django.contrib.gis.db import models
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _

from realtime.app_settings import ASH_EVENT_ID_FORMAT, ASH_EVENT_REPORT_FORMAT
from realtime.models.volcano import Volcano

__author__ = 'ismailsunni'
__project_name__ = 'inasafe-django'
__filename__ = 'ash'
__date__ = '7/15/16'
__copyright__ = 'imajimatika@gmail.com'


class Ash(models.Model):
    """Ash model."""
    class Meta:
        """Meta class."""
        app_label = 'realtime'
        verbose_name_plural = 'Ashes'

    volcano = models.ForeignKey(
        Volcano,
        related_name='ash',
        null=True)
    alert_level = models.CharField(
        verbose_name=_('Alert Level'),
        help_text=_('The alert level of the volcano ash event.'),
        max_length='30',
        blank=False
    )
    hazard_file = models.FileField(
        verbose_name=_('Hazard File'),
        help_text=_('Hazard file formatted as GeoTIFF (*.tif) in EPSG:4326.'),
        upload_to='ash/hazard_file/%Y/%m/%d',
        blank=False
    )
    impact_files = models.FileField(
        verbose_name=_('Impact Files'),
        help_text=_('Impact files processed zipped'),
        upload_to='ash/impact_files/%Y/%m/%d',
        blank=True,
        null=True
    )
    event_time = models.DateTimeField(
        verbose_name=_('Event Date and Time'),
        help_text=_('The time the ash happened.'),
        blank=False)
    event_time_zone_offset = models.IntegerField(
        verbose_name=_('Time Zone Offset'),
        help_text=_('The time zone offset of event time.'),
        default=0)
    event_time_zone_string = models.CharField(
        verbose_name=_('Time Zone String'),
        help_text=_('The time zone string of event time.'),
        max_length=255,
        blank=False,
        default='UTC')
    eruption_height = models.IntegerField(
        verbose_name=_(
            'Eruption height in metres (above vent height)'),
        blank=False,
        default=0)
    forecast_duration = models.IntegerField(
        verbose_name=_('Duration of forecast for Ash Hazard in days'),
        default=1)
    task_id = models.CharField(
        verbose_name=_('Celery task id'),
        help_text=_('Task id for processing'),
        max_length=255,
        default='',
        blank=True)
    task_status = models.CharField(
        verbose_name=_('Celery task status'),
        help_text=_('Task status for processing'),
        max_length=30,
        default='None',
        blank=True)

    objects = models.GeoManager()

    def __unicode__(self):
        ash_event = u'Ash event of [%s] [%s]' % (
            self.volcano, self.event_time)
        return ash_event

    def __init__(self, *args, **kwargs):
        super(Ash, self).__init__(*args, **kwargs)
        self.use_timezone()

    def use_timezone(self):
        """Use saved timezone information for event_time"""
        # Reformat event_time with timezone
        try:
            tz = pytz.timezone(self.event_time_zone_string)
            self.event_time = self.event_time.astimezone(tz)
        except BaseException:
            pass

    @property
    def event_id_formatted(self):
        return ASH_EVENT_ID_FORMAT.format(
            event_time=self.event_time,
            volcano_name=self.volcano.volcano_name)

    def delete(self, using=None):
        # delete all report
        if self.hazard_file:
            self.hazard_file.delete()
        if self.impact_files:
            self.impact_files.delete()
        return super(Ash, self).delete(using=using)


class AshReport(models.Model):
    """Ash Report Model."""

    class Meta:
        app_label = 'realtime'
        unique_together = (('ash', 'language'), )

    ash = models.ForeignKey(
        Ash,
        related_name='reports')
    language = models.CharField(
        verbose_name=_('Language ID'),
        help_text=_('The language ID of the report'),
        max_length=4,
        default='en'
    )
    report_map = models.FileField(
        verbose_name=_('Map PDF Report'),
        help_text=_('The map impact report stored as PDF'),
        upload_to='reports/ash/pdf'
    )

    @property
    def report_map_filename(self):
        """Return standardized filename for report map."""
        return ASH_EVENT_REPORT_FORMAT.format(
            event_time=self.ash.event_time,
            volcano_name=self.ash.volcano.volcano_name,
            language=self.language)

    @property
    def report_map_url(self):
        """Return url friendly address for report map"""
        event_time_format = '%Y%m%d%H%M%S%z'
        parameters = {
            'volcano_name': self.ash.volcano.volcano_name,
            'event_time': self.ash.event_time.strftime(event_time_format),
            'language': self.language
        }
        return reverse('realtime:ash_report_map', kwargs=parameters)

    def delete(self, using=None):
        self.report_map.delete()
        return super(AshReport, self).delete(using=using)

django_project/realtime/models/volcano.py
# coding=utf-8

from django.contrib.gis.db import models
from django.contrib.gis.gdal.datasource import DataSource
from django.contrib.gis.geos.geometry import GEOSGeometry
from django.contrib.gis.geos.point import Point
from django.utils.translation import ugettext_lazy as _

__author__ = 'Rizky Maulana Nugraha <lana.pcfre@gmail.com>'
__date__ = '7/18/16'


class Volcano(models.Model):
    """Volcano model."""

    class Meta:
        """Meta class."""
        app_label = 'realtime'
        verbose_name_plural = 'Volcanoes'

    volcano_name = models.CharField(
        verbose_name=_('The Volcano Name'),
        help_text=_('The name of the volcano'),
        max_length=50,
        blank=False)

    location = models.PointField(
        verbose_name=_('Location'),
        help_text=_('The location of the shake event in longitude and '
                    'latitude.'),
        srid=4326,
        null=False,
        blank=False)

    elevation = models.IntegerField(
        verbose_name=_('Volcano Elevation'),
        help_text=_('The elevation of the volcano in meters'),
        default=0
    )

    region = models.CharField(
        verbose_name=_('The region main name'),
        help_text=_('The region where the volcano located'),
        max_length=50,
        blank=True,
    )

    subregion = models.CharField(
        verbose_name=_('The sub region main name'),
        help_text=_('The sub region where the volcano located'),
        max_length=50,
        blank=True,
    )

    province = models.CharField(
        verbose_name=_('The province name'),
        help_text=_('The province where the volcano located'),
        max_length=50,
        blank=True,
    )

    district = models.CharField(
        verbose_name=_('The district name'),
        help_text=_('The district where the volcano located'),
        max_length=50,
        blank=True,
    )

    morphology = models.CharField(
        verbose_name=_('Morphology'),
        help_text=_('Morphology of the volcano'),
        max_length=50,
        blank=True
    )

    def __unicode__(self):
        return '%s - %s - %s' % (
            self.volcano_name, self.province, self.district)


def load_volcano_data(Volcano, volcano_shapefile):
    source = DataSource(volcano_shapefile)

    layer = source[0]

    for feat in layer:
        volcano_name = feat.get('volcano na')
        elevation = feat.get('elevation')
        region = feat.get('region')
        subregion = feat.get('subregion')
        morphology = feat.get('morphology')
        province = feat.get('province')
        district = feat.get('district')

        geometry = feat.geom

        geos_geometry = GEOSGeometry(geometry.geojson)

        if not isinstance(geos_geometry, Point):
            continue

        try:
            volcano = Volcano.objects.get(
                volcano_name__iexact=volcano_name,
                province__iexact=province,
                district__iexact=district,
                morphology__iexact=morphology,)
            print 'Volcano %s already exists' % volcano.volcano_name
        except Volcano.DoesNotExist:
            volcano = Volcano.objects.create(
                volcano_name=volcano_name,
                location=geos_geometry,
                elevation=elevation,
                region=region,
                subregion=subregion,
                morphology=morphology,
                province=province,
                district=district)
            print 'Volcano %s created' % volcano.volcano_name

django_project/realtime/templates/realtime/ash/index.html
{% extends "realtime/base.html" %}
{% load staticfiles %}
{% load leaflet_tags %}
{% load bootstrap %}
{% load pipeline %}
{% load i18n %}

{% get_language_info for LANGUAGE_CODE as language %}

{% block head_resources %}
    {{ block.super }}
    {% leaflet_js %}
    {% leaflet_css %}
    <!--[if lte IE 8]>
    <link rel="stylesheet" href="{% static 'realtime/css/MarkerCluster.user-map.ie.css' %}" />
    <![endif]-->
    {% stylesheet 'realtime_contrib' %}
    {% stylesheet 'realtime_appcss' %}
    {% stylesheet 'realtime_ashcss' %}
    {% stylesheet 'main' %}
    {{ form.media }}
{% endblock head_resources %}

{% block main_content %}
    <div class="row center-block">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h2 class="panel-title">{% trans "InaSAFE Volcanic Ash" %}</h2>
            </div>
            <div class="panel-body">
                <p class="text-justify">
                    {% blocktrans %}
                        This page contains <b>near realtime</b> volcanic ash
                        impact assessments generated prior to or during recent
                        volcanic ash eruptions in the Indonesia region.
                        Hazard maps of volcanic ash thickness on the ground
                        are produced by Indonesia’s Geological Agency,
                        Badan Geologi (<a href="http://www.bgl.esdm.go.id">http://www.bgl.esdm.go.id</a>)
                        and used by the Indonesian National Disaster Management Agency (BNPB)
                        to produce InaSAFE impact assessments
                        (<a href="http://www.bnpb.go.id">http://www.bnpb.go.id</a>
                        or <a href="http://realtime.inasafe.org">http://realtime.inasafe.org)</a>.
                        InaSAFE Realtime Volcanic Ash assessments estimate the potential impact of volcanic
                        ash on the ground. This information is used by disaster
                        managers to help them understand the potential scale of the volcanic ash impact
                        and to recommend mitigation activities for the most vulnerable communities.
                        This is particularly important in the lead up to an eruption when communities
                        have an opportunity to prepare for a possible hazard event.
                    {% endblocktrans %}
                </p>
            </div>
        </div>
    </div>
    <div class="row center-block">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title map-title">{% trans "Map" %}</h3>
            </div>
            <div class="panel-body" style="height: 500px">
                <!-- Leaflet Map div -->
                    {% leaflet_map "map" %}

                <!-- All the templates from view-->
            </div>

            {% if perms.realtime.add_ash %}
            <div class="panel-body">
                <a href="{% url "realtime:ash_upload_form" %}" class="btn btn-primary">{% trans "Upload Volcanic Ash" %}</a>
            </div>
            {% else %}
            <div class="panel-body">
                <a href="{% url "realtime_admin:login" %}?next={% url 'realtime:ash_upload_form' %}" class="btn btn-primary">{% trans "Log in to Upload Volcanic Ash" %}</a>
            </div>
            {% endif %}
        </div>
    </div>
{% endblock main_content %}

{% block table_content %}
    <div class="row center-block" id="realtime_table_div">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">{% trans "Ash Fall" %}</h3>
            </div>
            <div class="panel-body">
                <div class="col-md-12 table-responsive">
                    <table class="table table-striped table-bordered table-hover" id="realtime-table">
                        <thead>
                        <tr>
                            <th data-dynatable-column="event_time">{% trans "Time" %}</th>
                            <th data-dynatable-column="volcano_name">{% trans "Volcano Name" %}</th>
                            <th data-dynatable-column="alert_level">{% trans "Alert Level" %}</th>
                            <th data-dynatable-column="district">{% trans "District" %}</th>
                            <th data-dynatable-column="eruption_height">{% trans "Eruption Height" %}</th>
                        </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock table_content %}

{% block js_container %}
    {% javascript 'realtime_contrib' %}
    {% javascript 'realtime_appjs' %}
    {% javascript 'realtime_ashjs' %}
    <script type="text/javascript">
        var base_map;

        // Initialize Basemap Layer
        base_map = {
            {% for tile in leaflet_tiles %}
                '{{ tile.name }}': createBasemap(
                        '{{ tile.url }}',
                        '{{ tile.subdomains }}',
                        '{{ tile.attribution | safe }}')
                {% if not forloop.last %}
                    ,
                {% endif %}
            {% endfor %}
        };

        //Create Map with prepared base_map
        map = L.map('map', {
            layers: [base_map["{{ leaflet_tiles.0.name }}"]]
        });
        map.fitWorld().zoomIn();
        // make popup in center when opened
        map.on('popupopen', function (e) {
            var px = map.project(e.popup._latlng); // find the pixel location on the map where the popup anchor is
            px.y -= e.popup._container.clientHeight / 2; // find the height of the popup container, divide by 2, subtract from the Y axis of marker location
            map.panTo(map.unproject(px), {animate: true}); // pan to new center
        });

        //url to get json of events
        var get_events_url = '{% url "realtime:ash_feature_list" %}';

        var class_name = 'marker-cluster marker-cluster-project' + 1;
        markers = new L.markerClusterGroup({
            iconCreateFunction: (function (class_name) {
                return function (cluster) {
                    return L.divIcon({
                        html: '<div><span>' + cluster.getChildCount() + '</span></div>',
                        className: class_name,
                        iconSize: L.point(40, 40)
                    });
                }
            })(class_name),
            /*
            Disable clustering at specified zoom level.
            Useful to directly zoom to a particular event programmatically
            to expand the cluster
             */
            disableClusteringAtZoom: 10
        }).addTo(map);

        // create control layers
        L.control.layers(base_map, {
            'Volcanos': markers
        }, {
            position: 'topleft'
        }).addTo(map);

        var project_icon_path = "{% static 'realtime/img/volcano.svg' %}";
        var marker_icon = createIconMarker(
                project_icon_path);

        // create dynatable
        var jsonTableContents = [];
        var showEventHandler = createShowEventHandler(map, markers, map_events);

        {#  Use magic number 000 for placeholders #}
        var report_url = '{% url "realtime:ash_report_detail" volcano_name='VOLCANOTEMPLATENAME' event_time='1234567890123456789' language=language.code %}';
        var showReportHandler = createShowReportHandler(report_url);
        var downloadReportHandler = createDownloadReportHandler(report_url);
        var button_templates = [
            {
                type: 'simple-button',
                name: '{% trans "Zoom" %}',
                css_class: 'glyphicon glyphicon-search',
                handler: 'showEventHandler'
            },
            {
                type: 'simple-button',
                name: '{% trans "Report" %}',
                css_class: 'glyphicon glyphicon-file',
                handler: 'showReportHandler'
            },
            {
                type: 'dropdown',
                name: '{% trans "Download" %}',
                css_class: 'glyphicon glyphicon-download',
                actions: [
                    {
                        active: function(event){return event.hazard_file != undefined;},
                        text: '{% trans "Hazard File" %}',
                        href:  function(event){return event.hazard_file;},
                        download: function(event){return event.event_id_formatted+'-hazard.tif';}
                    },
                    {
                        active: function(event){return event.impact_files != undefined;},
                        text: '{% trans "Impact Files" %}',
                        href:  function(event){return event.impact_files;},
                        download: function(event){return event.event_id_formatted+'-impact.zip';}
                    },
                    {
                        text: '{% trans "Report" %}',
                        handler: 'downloadReportHandler'
                    }
                ]
            }
        ];

        function getAshEventsJson(event_json){
            markers.clearLayers();
            L.geoJson(event_json, {
                onEachFeature: onEachFeature,
                pointToLayer: function (feature, latlng) {
                    var marker = L.marker(latlng, {icon: marker_icon});
                    map_events[feature.id] = marker;
                    return marker;
                }
            }).addTo(markers);
            jsonTableContents = [];
            for (var i = 0; i < event_json.features.length; ++i) {
                jsonTableContents[i] = event_json.features[i].properties;
            }
            dynaTable.settings.dataset.originalRecords = jsonTableContents;
            dynaTable.paginationPerPage.set(10);
            dynaTable.sorts.add('event_time', -1);
            dynaTable.process();

            if(jsonTableContents.length > 0){
                var event_id = jsonTableContents[0].id;
                showEventHandler(event_id);
            }
        }

        function onEachFeature(feature, layer) {
            // add feature to map_events index
            // Set the popup content if it does have the content
            if (feature.properties) {
                var properties = feature.properties;
                properties.id = feature.id;
                properties.volcano_name = properties.volcano.volcano_name;
                properties.district = properties.volcano.district;
                var popup_content = window.JST.popup_content(properties);
                layer.bindPopup(popup_content);
            }
        }

        $(document).ready(function(){

            var $root = $('html, body');
            var $navbar = $("#navbar");

            dynaTable = $('#realtime-table').dynatable({
                features: {
                    pushState: false
                },
                table: {
                    defaultColumnIdStyle: 'underscore'
                },
                writers: {
                    _rowWriter: createActionRowWriter(button_templates, '{% trans "YYYY-MM-DD [at] HH:mm:ss ZZ" %}')
                },
                dataset: {
                    records: jsonTableContents
                }
            }).data('dynatable');

            // add action column to dynatable
            addActionColumn("#realtime-table", "Action");

            $.get(get_events_url, function (data) {
                event_json = data;
                getAshEventsJson(data);
            });
        });
    </script>
{% endblock js_container %}