django_project/core/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from django.views.i18n import javascript_catalog
from realtime.admin import realtime_admin_site


js_info_dict = {
    'packages': ('realtime',),
}

urlpatterns = patterns(
    '',

    url(r'^admin/', include(admin.site.urls)),

    # uncomment to enable defaut Django auth
    # url(r'^accounts/login/$', 'django.contrib.auth.views.login'),

    # include application urls
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'', include('frontend.urls', namespace='front_end')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^mce_filebrowser/', include('mce_filebrowser.urls')),
    url(r'^user-map/', include('user_map.urls', namespace='user_map')),
    url(r'^jsi18n/$', javascript_catalog, js_info_dict),
    url(r'^realtime/', include('realtime.urls', namespace='realtime')),
    url(r'^realtime/api-auth/', include(
        'rest_framework.urls', namespace='rest_framework')),
    # alias for auth in realtime
    url(r'^realtime/api/v1/auth/', include(
        'rest_framework.urls', namespace='rest_framework')),
    url(r'^realtime/admin/', include(realtime_admin_site.urls)),

    # url pattern for realtime reports
    url(r'', include('realtime.report_urls', namespace='realtime_report')),

    # url pattern for realtime flatpages
    # not appending slash because flatpages url starts with one
    url(r'^realtime/pages', include('django.contrib.flatpages.urls')),
)

# expose static files and uploded media if DEBUG is active
if settings.DEBUG:
    urlpatterns += patterns(
        '',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {
                'document_root': settings.MEDIA_ROOT,
                'show_indexes': True
            }),
        url(r'', include('django.contrib.staticfiles.urls'))
    )
else:
    # for production mode
    # Although it will also be served by nginx
    # Useful for testing production environment in local configuration
    urlpatterns += patterns(
        '',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {
                'document_root': settings.MEDIA_ROOT,
                'show_indexes': False
            }),
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
            {
                'document_root': settings.STATIC_ROOT,
                'show_indexes': False
            }),
    )

django_project/user_map/urls.py
# coding=utf-8
"""URI Routing configuration for this apps."""
from django.conf.urls import patterns, url

urlpatterns = patterns(
    '',
    url(r'^$', 'user_map.views.index', name='index'),
    url(r'^users.json', 'user_map.views.get_users', name='get_users'),

    url(r'^register$', 'user_map.views.register', name='register'),
    url(r'^account-confirmation/(?P<uid>[0-9A-Za-z_\-]+)/(?P<key>.+)/$',
        'user_map.views.confirm_registration',
        name='confirm_registration'),

    url(r'^login$', 'user_map.views.login', name='login'),
    url(r'^logout$', 'user_map.views.logout', name='logout'),
    url(r'^update-profile$', 'user_map.views.update_user', name='update_user'),
    url(r'^delete-user$', 'user_map.views.delete_user', name='delete_user'),

    url(r'^password-reset/$', 'user_map.views.password_reset',
        name='password_reset'),
    url(r'^password-reset/done/$', 'user_map.views.password_reset_done',
        name='password_reset_done'),
    url(r'^password-reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
        'user_map.views.password_reset_confirm',
        name='password_reset_confirm'),
    url(r'^password-reset/complete/$',
        'user_map.views.password_reset_complete',
        name='password_reset_complete'),

    url(r'^download$', 'user_map.views.download', name='download'),
)

django_project/user_map/models/inasafe_role.py
# coding=utf-8
"""Model class for InaSAFE Role"""
from django.contrib.gis.db import models


class InasafeRole(models.Model):
    """InaSAFE Role for users e.g. InaSAFE developer, trainer, user."""
    class Meta:
        """Meta class."""
        app_label = 'user_map'

    name = models.CharField(
        help_text='How would you define your InaSAFE Role in this project?',
        max_length=100,
        null=False,
        blank=False)
    badge = models.CharField(
        help_text='The path to the badge',
        max_length=200,
        null=False,
        blank=False)
    sort_number = models.IntegerField(
        help_text='Sorting order for role in role list.',
        null=True,
        blank=True)

    def __unicode__(self):
        return self.name

django_project/user_map/models/osm_role.py
# coding=utf-8
"""Model class for OSM Role"""
from django.contrib.gis.db import models


class OsmRole(models.Model):
    """OSM Role for users e.g. OSM Mapper, Trainer."""
    class Meta:
        """Meta class."""
        app_label = 'user_map'

    name = models.CharField(
        help_text='How would you define your OSM Role in this project?',
        max_length=100,
        null=False,
        blank=False)
    badge = models.CharField(
        help_text='The path to the badge',
        max_length=100,
        null=False,
        blank=False)
    sort_number = models.IntegerField(
        help_text='Sorting order for role in role list.',
        null=True,
        blank=True)

    def __unicode__(self):
        return self.name

django_project/user_map/forms/custom_widget.py
from django.utils.safestring import mark_safe
from django.utils.html import escape, conditional_escape
from django.utils.encoding import force_unicode
from django.forms.widgets import ClearableFileInput, Input, CheckboxInput


class CustomClearableFileInput(ClearableFileInput):
    """A custom ClearableFileInput widget.

    ..note:: Adapted from django.forms.widgets.ClearableFileInput and also
        utilising img-responsive bootstrap class.
    """
    def render(self, name, value, attrs=None):
        """Render the custom widget."""
        substitutions = {
            'input_text': self.input_text,
            'clear_template': '',
            'clear_checkbox_label': self.clear_checkbox_label,
        }
        template = '%(input)s'
        substitutions['input'] = Input.render(self, name, value, attrs)

        if value and hasattr(value, "url"):
            template = ('%(initial)s %(clear_template)s<br />%(input_text)s: '
                        '%(input)s')
            substitutions['initial'] = (
                '<img class="img-responsive" src="%s" alt="%s"/>' % (
                    escape(value.url), escape(force_unicode(value))))
            if not self.is_required:
                checkbox_name = self.clear_checkbox_name(name)
                checkbox_id = self.clear_checkbox_id(checkbox_name)
                substitutions['clear_checkbox_name'] = conditional_escape(
                    checkbox_name)
                substitutions['clear_checkbox_id'] = conditional_escape(
                    checkbox_id)
                substitutions['clear'] = CheckboxInput().render(
                    checkbox_name, False, attrs={'id': checkbox_id})
                substitutions['clear_template'] = \
                    self.template_with_clear % substitutions
        return mark_safe(template % substitutions)

django_project/user_map/views.py
# coding=utf-8
"""Views of the apps."""
import unicodecsv as csv

from django.shortcuts import render, render_to_response
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.template import RequestContext, loader
from django.forms.util import ErrorList
from django.forms.forms import NON_FIELD_ERRORS
from django.core.urlresolvers import reverse
from django.core.mail import send_mail
from django.contrib import messages
from django.contrib.auth import (
    login as django_login,
    authenticate,
    logout as django_logout)
from django.contrib.auth.views import (
    password_reset as django_password_reset,
    password_reset_done as django_password_reset_done,
    password_reset_confirm as django_password_reset_confirm,
    password_reset_complete as django_password_reset_complete)
from django.contrib.auth.forms import PasswordChangeForm, SetPasswordForm
from django.contrib.auth.decorators import login_required
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.sites.models import get_current_site
from realtime.app_settings import REST_GROUP

from user_map.forms.user import (
    RegistrationForm,
    LoginForm,
    BasicInformationForm,
    CustomPasswordResetForm)
from user_map.models.user import User
from user_map.app_settings import (
    PROJECT_NAME,
    PROJECTS,
    INASAFE_CERTIFIED_TRAINER_BADGE,
    OSM_CERTIFIED_TRAINER_BADGE,
    DEFAULT_FROM_MAIL,
    LEAFLET_TILES, MAPQUEST_MAP_KEY)
from user_map.utilities.decorators import login_forbidden


def index(request):
    """Index page of user map.

    :param request: A django request object.
    :type request: request

    :returns: Response will be a nice looking map page.
    :rtype: HttpResponse
    """
    information_modal = loader.render_to_string(
        'user_map/information_modal.html')
    data_privacy_content = loader.render_to_string(
        'user_map/data_privacy.html')

    user_menu_button = loader.render_to_string(
        'user_map/user_menu_button.html', {'user': request.user})

    legend = loader.render_to_string(
        'user_map/legend.html', {'projects': PROJECTS})

    leaflet_tiles = dict(
        name=LEAFLET_TILES[0],
        url=LEAFLET_TILES[1],
        subdomains=LEAFLET_TILES[2],
        attribution=LEAFLET_TILES[3]
    )
    #
    # projects = [{
    #     'name': p['name'],
    #     'icon': do_static(p['icon']),
    #     'shadow_icon': do_static(p['shadow_icon']),
    #     'icon_size': p['icon_size']
    # } for p in PROJECTS]

    context = {
        'data_privacy_content': data_privacy_content,
        'information_modal': information_modal,
        'user_menu_button': user_menu_button,
        'projects': PROJECTS,
        'legend': legend,
        'leaflet_tiles': leaflet_tiles,
        'mapquest_key': MAPQUEST_MAP_KEY
    }
    return render(request, 'user_map/index.html', context)


def get_users(request):
    """Return a json document of users of the project.

    Users will belong to InaSAFE layer if they only have InaSAFE roles. If
    they have OSM role(s), they will belong to OSM layers.

    This will only fetch users who have approved the registration by email and
    still active.

    :param request: A django request object.
    :type request: request
    """

    if request.method == 'GET':

        # Get data:
        project = str(request.GET.get('project', ''))

        if project.lower() == 'inasafe':
            # only inasafe users
            users = User.objects.filter(
                is_confirmed=True,
                is_active=True,
                osm_roles=None).exclude(
                inasafe_roles=None).exclude(groups__name=REST_GROUP)
        elif project.lower() == 'openstreetmap':
            # only osm users
            users = User.objects.filter(
                is_confirmed=True,
                is_active=True,
                inasafe_roles=None).exclude(osm_roles=None).exclude(
                groups__name=REST_GROUP)
        else:
            # get users who have both roles
            users = User.objects.filter(
                is_confirmed=True, is_active=True).exclude(
                osm_roles=None).exclude(inasafe_roles=None).exclude(
                groups__name=REST_GROUP)

        context = {
            'users': users,
            'inasafe_cert_trainer_badge': INASAFE_CERTIFIED_TRAINER_BADGE,
            'osm_cert_trainer_badge': OSM_CERTIFIED_TRAINER_BADGE
        }
        users_json = loader.render_to_string(
            'user_map/users.json',
            context_instance=RequestContext(request, context))

        # Return Response
        return HttpResponse(users_json, content_type='application/json')
    else:
        raise Http404


@login_forbidden
def register(request):
    """User registration view.

    :param request: A django request object.
    :type request: request
    """
    if request.method == 'POST':
        form = RegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            form.save_m2m()

            current_site = get_current_site(request)
            domain = current_site.domain
            context = {
                'project_name': PROJECT_NAME,
                'protocol': 'http',
                'domain': domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'user_name': user.name,
                'key': user.key
            }
            email = loader.render_to_string(
                'user_map/account/registration_confirmation_email.html',
                context)

            subject = '%s User Registration' % PROJECT_NAME
            sender = '%s - No Reply <%s>' % (PROJECT_NAME, DEFAULT_FROM_MAIL)
            send_mail(
                subject, email, sender, [user.email], fail_silently=False)

            messages.success(
                request,
                ('Thank you for registering in our site! Please check your '
                 'email to confirm your registration'))
            return HttpResponseRedirect(reverse('user_map:register'))
    else:
        form = RegistrationForm()
    return render_to_response(
        'user_map/account/registration.html',
        {'form': form},
        context_instance=RequestContext(request)
    )


@login_forbidden
def confirm_registration(request, uid, key):
    """The view containing form to reset password and process it.

    :param request: A django request object.
    :type request: request

    :param uid: A unique id for a user.
    :type uid: str

    :param key: Key to confirm the user.
    :type key: str
    """
    decoded_uid = urlsafe_base64_decode(uid)
    try:
        user = User.objects.get(pk=decoded_uid)

        if not user.is_confirmed:
            if user.key == key:
                user.is_confirmed = True
                user.save(update_fields=['is_confirmed'])
                information = (
                    'Congratulations! Your account has been successfully '
                    'confirmed. Please continue to log in.')
            else:
                information = (
                    'Your link is not valid. Please make sure that you use '
                    'confirmation link we sent to your email.')
        else:
            information = ('Your account is already confirmed. Please '
                           'continue to log in.')
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        information = ('Your link is not valid. Please make sure that you use '
                       'confirmation link we sent to your email.')

    context = {
        'page_header_title': 'Registration Confirmation',
        'information': information
    }
    return render_to_response(
        'user_map/information.html',
        context,
        context_instance=RequestContext(request)
    )


@login_forbidden
def login(request):
    """Login view.

    :param request: A django request object.
    :type request: request
    """
    if request.method == 'POST':
        next_page = request.GET.get('next', '')
        if next_page == '':
            next_page = reverse('user_map:index')
        form = LoginForm(data=request.POST)
        if form.is_valid():
            user = authenticate(
                email=request.POST['email'],
                password=request.POST['password']
            )
            if user is not None:
                if user.is_active and user.is_confirmed:
                    django_login(request, user)

                    return HttpResponseRedirect(next_page)
                if not user.is_active:
                    errors = form._errors.setdefault(
                        NON_FIELD_ERRORS, ErrorList())
                    errors.append(
                        'The user is not active. Please contact our '
                        'administrator to resolve this.')
                if not user.is_confirmed:
                    errors = form._errors.setdefault(
                        NON_FIELD_ERRORS, ErrorList())
                    errors.append(
                        'Please confirm you registration email first!')
            else:
                errors = form._errors.setdefault(
                    NON_FIELD_ERRORS, ErrorList())
                errors.append(
                    'Please enter a correct email and password. '
                    'Note that both fields may be case-sensitive.')
    else:
        form = LoginForm()

    return render_to_response(
        'user_map/account/login.html',
        {'form': form},
        context_instance=RequestContext(request))


def logout(request):
    """Log out view.

    :param request: A django request object.
    :type request: request
    """
    django_logout(request)
    return HttpResponseRedirect(reverse('user_map:index'))


@login_required(login_url='user_map:login')
def update_user(request):
    """Update user view.

django_project/user_map/templates/user_map/base.html
{% load staticfiles %}
{% load pipeline %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <link rel="shortcut icon" href="{% static FAVICON_PATH %}">
    <link rel='stylesheet' id='redux-google-fonts-shoestrap-css' href='http://fonts.googleapis.com/css?family=Ubuntu%3A300%2C700%2C500&#038;ver=1435673986' type='text/css' media='all'/>
    <title>{% block title %} {{ PROJECT_NAME }} User Map{% endblock %}</title>

    {% block head_resources %}
        <!--Base Stylesheet -->
        {% stylesheet 'contrib' %}

        <!-- Base Javascript -->
        {% javascript 'contrib' %}
    {% endblock head_resources %}

    <!-- Google Analytics -->
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-93181136-1', 'auto');
        ga('send', 'pageview');
    </script>
</head>

<body>
<div class="user_map_navbar ">
    {% block navbar %}
        <header id="banner-header" class="banner navbar navbar-default
    topnavbar navbar-fixed-top default" role="banner">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" rel="home" href="http://inasafe.org" title="InaSAFE">
                        <img id="site-logo" style="max-width:100px;
                    margin-top:-7px;" src=
                                "{% static BRAND_LOGO %}">
                    </a>
                </div>
                {% block nav_main %}
                    <nav class="nav-main navbar-collapse collapse" role="navigation">
                        <ul id="menu-default" class="navbar-nav nav">
                            <li class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-151 current_page_item menu-item-152 menu-for-users">
                                <a title="For Users" href="http://blogtest.inasafe.org/for-users/">For Users</a>
                            </li>
                            <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-155 menu-for-contributors dropdown">
                                <a title="For Contributors" href="#" data-toggle="dropdown" class="dropdown-toggle" aria-haspopup="true">For Contributors
                                    <span class="caret"></span></a>
                                <ul role="menu" class=" dropdown-menu">
                                    <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-171 menu-coders">
                                        <a title="Coders" href="http://blogtest.inasafe.org/for-contributors/for-coders/">Coders</a>
                                    </li>
                                    <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-170 menu-writers-and-designers">
                                        <a title="Writers and Designers" href="http://blogtest.inasafe.org/for-contributors/for-documentation-writers-and-designers/">Writers and Designers</a>
                                    </li>
                                    <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-169 menu-translators">
                                        <a title="Translators" href="http://blogtest.inasafe.org/for-contributors/for-translators/">Translators</a>
                                    </li>
                                </ul>
                            </li>
                            <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-158 menu-blog">
                                <a title="Blog" href="http://blogtest.inasafe.org/blog/">Blog</a>
                            </li>
                            <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-12 menu-chat-live">
                                <a title="Chat Live!" href="http://blogtest.inasafe.org/chat-live/">Chat Live!</a>
                            </li>
                            <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-160 menu-report-an-issue">
                                <a title="Report an Issue" target="_blank" href="https://github.com/AIFDR/inasafe/issues">Report an Issue</a>
                            </li>
                        </ul>
                        <div id="lang_sel">
                            <ul>
                                <li>
                                    <a href="#" class="lang_sel_sel icl-en">English</a>
                                </li>
                            </ul>
                        </div>
                        <div class="nav navbar-nav pull-right">
                            {% if not user.is_authenticated %}
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle"
                                       data-toggle="dropdown"><b>Account</b>
                                        <b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li>
                                            <a href="{% url 'user_map:login' %}">
                                                Log In
                                            </a>
                                        </li>
                                        <li>
                                            <a href="{% url 'user_map:register' %}">
                                                Sign Up
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                            {% endif %}
                            {% if user.is_authenticated %}
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b>Hi, {{ user.name }}</b>
                                        <b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li>
                                            <a href="{% url 'user_map:update_user' %}">Edit Profile</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'user_map:logout' %}">Log Out</a>
                                        </li>
                                    </ul>
                                </li>
                            {% endif %}
                        </div>
                    </nav>
                {% endblock %}
            </div>
            <div class="second-menu">
                <div class="container" style="min-height: 10px">
                    {% block nav_second %}
                    {% endblock %}
                </div>
            </div>
            <div style="clear: both;"></div>
        </header>
    {% endblock navbar %}
</div>

{% block main_content %}
{% endblock main_content %}

{% block footer %}
{% endblock footer %}

{% block js_container %}
{% endblock js_container %}
</body>
</html>

django_project/user_map/templates/user_map/base_page.html
{% extends "user_map/base.html" %}
{% load staticfiles %}
{% load pipeline %}

{% block head_resources %}
    {{ block.super }}
    {% stylesheet 'main' %}
    {% stylesheet 'usermap_appcss' %}
{% endblock head_resources %}


{% block main_content %}
{% endblock main_content %}

{% block footer %}
    <div class="container">
        <hr>
        <div class="footer centered">
            © 2014 InaSAFE User Map. All rights reserved.
        </div>
    </div>
{% endblock footer %}

{% block js_container %}
    <script type="text/javascript">
        var setElementHeight = function () {
            var height = $(window).height();
            $('.autoheight').css('min-height', (height - 250));
        };

        $(window).on("resize", function () {
            setElementHeight();
        }).resize();
    </script>
{% endblock js_container %}

django_project/user_map/templates/user_map/data_privacy.html
<script id="data-privacy-content-section" type="text/template">
  The data you enter on this site may be visible to others. We suggest that
  you approximate your physical location to the nearest
  town or major center. Parts of your data will be made available for
  others to download and use. We will <strong>not</strong> share:</br>
  <ul>
    <li>your email address</li>
    <li>your password</li>
  </ul>
  If you would like your data removed from this site, please log in to your
  account.
</script>

django_project/user_map/templates/user_map/information.html
{% extends "user_map/base_page.html" %}

{% block main_content %}
  <div class="container autoheight">
    <div class="page-header">
      <h2>{{ page_header_title }}
        {% if page_header_description %}
          <br>
          <small>{{ page_header_description }}</small>
        {% endif %}
      </h2>
    </div>
    {{ information }}
  </div>
{% endblock main_content %}

django_project/user_map/templates/user_map/information_modal.html
  <!-- Modal for showing global information -->
  <div class="modal fade" id="information-modal" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h3 class="modal-title"></h3>
        </div>
        <div class="modal-body">
          <p id="info_content">
          </p>
        </div>
        <div class="modal-footer">
          <button class="btn btn-primary" data-dismiss="modal" aria-hidden="true">
            OK
          </button>
        </div>
      </div>
    </div>
  </div>

django_project/user_map/templates/user_map/legend.html
{% load staticfiles %}
<script id="legend" type="text/template">
  <h4>Legend</h4>
  {% for project in projects %}
      <img height='30' width='20' src='{% static project.icon %}'> {{project.name }}<br>
  {% endfor %}
</script>

django_project/user_map/templates/user_map/user_menu_button.html
{% if not user.is_authenticated %}
<script id="user-menu-add-button" type="text/template">
  <button type="button" class="btn btn-default btn-sm user-menu-control"
          id="add-user-button" onclick="window.open('{% url "user_map:register" %}', '_self');"
          data-toggle="tooltip" data-original-title="Add me to map!">
    <span class="glyphicon glyphicon-user"></span>
  </button>
</script>
{% else %}
<script id="user-menu-edit-button" type="text/template">
  <button type="button" class="btn btn-default btn-sm user-menu-control"
          id="edit-user-button" onclick="window.open('{% url "user_map:update_user" %}', '_self');""
          data-toggle="tooltip" data-original-title='Edit my profile!'>
    <span class='glyphicon glyphicon-pencil'></span>
  </button>
</script>
{% endif %}

{% if user.is_authenticated %}
  <script id="user-menu-delete-button" type="text/template">
    <button type="button" class="btn btn-default btn-sm user-menu-control"
            id="delete-user-button"
            onclick="window.open('{% url "user_map:update_user" %}#account-setting', '_self');""
            data-toggle="tooltip" data-original-title="Delete me from the map!">
      <span class="glyphicon glyphicon-trash"></span>
    </button>
  </script>
{% endif %}

<script id="user-menu-download-button" type="text/template">
  <button type="button" class="btn btn-default btn-sm user-menu-control"
          id="download-button" onclick="window.open('{% url "user_map:download" %}', '_self');"
          data-toggle="tooltip"
          data-original-title="Download all users as CSV file!">
    <span class="glyphicon glyphicon-download-alt"></span>
  </button>
</script>

{% if not user.is_authenticated %}
<script id="user-menu-forgot-button" type="text/template">
  <button type="button" class="btn btn-default btn-sm user-menu-control"
          id="forgot-button" onclick="window.open('{% url "user_map:password_reset" %}', '_self');"
          data-toggle="tooltip"
          data-original-title="Forgot your password?">
    <span class="glyphicon glyphicon-question-sign"></span>
  </button>
</script>
{% endif %}